### ISSUE TITLE
Playing with branches

### ISSUE THREAD

**Issue by TheRealSibasishBehera** [opencodeiiita/GoGit-3.0#399]
Create a new branch from the initial commit of this repo and name it "initial-branch".
Then answer the following question in your info.md file.

`Ques` - You will see that some repo on GitHub has a main branch as their main but some have a master branch as their main branch. So, please explain in which case Git/GitHub creates main as the main branch and in which case it creates master as the main branch.

Now add and commit your answer to this question and create a PR from this initial branch to this repo's dummy-branch.
Condition: You must use the **SHA key of the initial commit** in any one of the git commands that you will use to complete this task.
PR which will be unable to fulfill the condition can be rejected.
If your `info.md` file is not there, then you have to make a new one.
No need to claim the issue, First correct PR will be merged.
**Make sure to add the commands you used in the PR description. 
Failing to do so, Your PR won't be merged**

**Comment by Nandinig24** [comment]
deadline?
